<?php

/**
 * @file
 * Functionality for the Style guide module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function server_style_guide_theme() {
  $info = [];

  // A helper twig showing the available text styles.
  $info['server_style_guide_text_styles'] = [
    'variables' => [],
  ];

  $info['server_style_guide_header'] = [
    'variables' => [
      'title' => NULL,
      // The unique HTML id (e.g. `#foo`). We don't use the reserved `#id`.
      'unique_id' => NULL,
      // Optional; a link to the design.
      'link' => NULL,
    ],
  ];

  // Wrap all style guide elements.
  $info['server_style_guide_wrapper'] = [
    'variables' => [
      'elements' => [],
    ],
  ];

  // A single element wrapper, with no container.
  $info['server_style_guide_no_container'] = [
    'variables' => [
      'title' => NULL,
      'element' => [],
    ],
  ];

  // A single element wrapper, with a wide container.
  $info['server_style_guide_container_wide'] = [
    'variables' => [
      'title' => NULL,
      'element' => [],
    ],
  ];

  // A person container.
  $info['server_style_guide_person'] = [
    'variables' => [
      'image' => NULL,
      'name' => NULL,
      'job_title' => NULL,
      'role' => NULL,
      'email' => NULL,
      'phone' => NULL,
    ],
  ];

  // A person title.
  $info['server_style_guide_person_title'] = [
    'variables' => [
      'title' => NULL,
      'text_size' => NULL,
      'text_font' => NULL,
    ],
  ];
  // A person button.
  $info['server_style_guide_person_button'] = [
    'variables' => [
      'title' => NULL,
    ],
  ];

  return $info;
}

/**
 * Implements hook_toolbar().
 */
function server_style_guide_toolbar() {
  $items = [];
  $items['style_guide'] = [
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
  ];

  if (!\Drupal::currentUser()->hasPermission('access content')) {
    return $items;
  }

  $items['style_guide'] += [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Style Guide'),
      '#url' => Url::fromRoute('server_style_guide.style_guide'),
      '#attributes' => [
        'class' => ['toolbar-icon', 'toolbar-icon-style-guide'],
        'id' => 'toolbar-tab-style-guide',
      ],
    ],
    '#wrapper_attributes' => [
      'class' => ['style-guide-toolbar-tab'],
    ],
    '#attached' => [
      'library' => [
        'server_style_guide/toolbar',
      ],
    ],
  ];

  return $items;
}
